version: '3'
services:
  block-builder:
    build:
      context: block-builder
      dockerfile: Dockerfile
      args:
        - BLOCK=${BLOCK}
        - MACHINE=${MACHINE}
        - VERBOSE=${VERBOSE}

    labels:
      - 'io.balena.image.class=overlay'
      - 'io.balena.image.requires-reboot=1'
      - 'io.balena.image.store=data'

